apps/game/urls.py
from django.urls import path,include
from .views import *

app_name='game'

urlpatterns = [
    path('',main,name='main'),
    # path('attack_main/', main, name='attack_main'),
    path('attack', attack, name ='attack'),
    path('attack_choice', attack_choice, name ='attack_choice'),
    path('attacking/<int:pk>', attacking, name ='attacking'),
    path('list/', game_list , name='list'),
#     path('detail/<int:pk>/', detail, name='detail'),
    # path('detail/<int:pk>/', detail, name='detail'),
    path('detail/<int:pk>', game_detail, name='detail'),
#     path('defend/<int:pk>/', defend, name="defend"),
    path('defend/<int:pk>', defend, name="defend"),
    path('delete/<int:pk>', game_delete, name='delete')
]

apps/users/urls.py
from django.urls import path
from .views import *

app_name='users'

urlpatterns = [
    path("",main,name='main'),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("signup/", signup, name="signup"),
    path("ranking/", ranking, name="ranking"),
    path("set_name/", set_name, name="setname"),
    path('delete/<int:pk>/', delete, name ='delete'),
    path('update/<int:pk>/', update, name ='update'),
    #path('detail/<int:pk>/', detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.game.urls')),
    path('users/',include('apps.users.urls')),
    path('accounts/', include('allauth.urls')),
]

apps/game/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
import random

class Game(models.Model):
    now = models.BooleanField('경기상태', default=False)
    attack_num = models.IntegerField('공격숫자', default=0, validators=[MinValueValidator(1), MaxValueValidator(10)])
    defend_num = models.IntegerField('수비숫자', default=0, validators=[MinValueValidator(1), MaxValueValidator(10)])
    attack_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='attack_games', verbose_name='공격자')
    defend_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='defend_games', verbose_name='수비자')
    game_num = models.IntegerField()
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.game_num = random.randint(1, 2)
        super().save(*args, **kwargs)

apps/game/forms.py
from django import forms
from apps.users.models import User
from .models import Game
import random

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['attack_num','defend_user']

    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('current_user', None) 
        super(GameForm, self).__init__(*args, **kwargs)
    
        if current_user:
            self.fields['defend_user'].queryset = User.objects.exclude(id=current_user.id)
    
        random_choices = random.sample(range(1, 11), 5)
        self.fields['attack_num'].widget = forms.Select(choices=[(i, str(i)) for i in random_choices])

class DefendForm(forms.ModelForm):
    class Meta:
        model=Game
        fields = ['defend_num']

    def __init__(self, *args, **kwargs):
        super(DefendForm, self).__init__(*args, **kwargs)
        random_choices = random.sample(range(1, 11), 5)
        self.fields['defend_num'].widget = forms.Select(choices=[(i, str(i)) for i in random_choices])

apps/game/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from apps.users.models import User
from .models import *
import random
from .forms import *
from django.contrib import auth

def main(request):
    return render(request, 'game/game_main.html')

def defend(request, pk):
    game = Game.objects.get(id=pk)
    if request.method == 'GET':
        counter = request.GET.get('counter', None)
        form = DefendForm(instance=game)
        ctx = {
            'form': form,
            'pk': pk,
            'counter': counter
        }
        return render(request, 'game/game_defend.html', ctx)
    form = DefendForm(request.POST, instance=game)
    if form.is_valid():
        form.save()
    game.now = True
    game.save()


    counter = request.POST['counter']

    users = User.objects.all()
    user_game = Game.objects.get(id=pk)
    user_nickname = auth.get_user(request).nickname
    user_num = 0
    enemy = ''
    enemy_num = 0
    winner=''

    if user_game.attack_user.nickname == user_nickname:
        user_num = user_game.attack_num
        enemy = user_game.defend_user.nickname
        enemy_num = user_game.defend_num
    else:
        user_num = user_game.defend_num
        enemy = user_game.attack_user.nickname
        enemy_num = user_game.attack_num

    if user_game.game_num == 1:
        if user_num < enemy_num:
            winner = user_nickname
        elif user_num > enemy_num:
            winner = enemy
    else:
        if user_num < enemy_num:
            winner = enemy
        elif user_num > enemy_num:
            winner = user_nickname

    me = users.get(nickname=user_nickname)
    other = users.get(nickname=enemy)
    if winner == user_nickname:
        me.points += user_num
        other.points -= enemy_num
    elif winner == enemy:
        me.points -= user_num
        other.points += enemy_num

    me.save()
    other.save()

    return redirect(f'../detail/{pk}?counter={counter}')

def attack(request):
    return render(request, 'game/game_attacking.html')

def attack_choice(request):
    if request.method == 'POST':
        form = GameForm(request.POST, current_user=request.user)
        if form.is_valid():
            game = form.save(commit=False)
            game.attack_user = request.user
            game.save()
            return redirect('game:list')
    else:
        form = GameForm(current_user=request.user)

    games = Game.objects.all()
    game = games.last()  # 가장 최근에 생성된 게임 객체를 가져옵니다.
    ctx = {'games': games, 'form': form, 'game': game}
    return render(request, 'game/game_attack.html', ctx)



def attacking(request, pk):
    game = Game.objects.get(id=pk)
    ctx = {'game': game}
    
    if game.attack_num == 0 or game.defend_num == 0:
        game.game_now = False
    else :
        if game.game_num == 1:
            # 게임 1: 수가 클 때 이기는 게임
            if game.attack_num > game.defend_num:
                ctx['game_result'] = "수가 클 때 이깁니다! {}승!".format(game.attack_user)
            else:
                ctx['game_result'] = "수가 클 때 이깁니다! {}승!".format(game.defend_user)
        else:
            # 게임 2: 수가 작을 때 이기는 게임
            if game.attack_num < game.defend_num:
                ctx['game_result'] = "수가 작을 때 이깁니다! {}승!".format(game.attack_user)
            else:
                ctx['game_result'] = "수가 작을 때 이깁니다! {}승!".format(game.defend_user)
        
        game.game_now = True
    game.save()
    return render(request, 'game/game_attacking.html', ctx)

def game_list(request):
    games = Game.objects.all()
    user_id = auth.get_user(request).id
    user_games = games.filter(models.Q(attack_user=user_id) | models.Q(defend_user=user_id))
    user_games = user_games.order_by("-id")
    ctx = {
        'user_games': user_games
    }
    return render(request, 'game/game_list.html', ctx)

def game_detail(request, pk):
    users = User.objects.all()
    user_game = Game.objects.get(id=pk)
    user_nickname = auth.get_user(request).nickname
    counter = request.GET.get('counter', None)
    user_num = 0
    enemy = ''
    enemy_num = 0
    winner=''

    if user_game.attack_user.nickname == user_nickname:
        user_num = user_game.attack_num
        enemy = user_game.defend_user.nickname
        enemy_num = user_game.defend_num
    else:
        user_num = user_game.defend_num
        enemy = user_game.attack_user.nickname
        enemy_num = user_game.attack_num

    if user_game.game_num == 1:
        if user_num < enemy_num:
            winner = user_nickname
        elif user_num > enemy_num:
            winner = enemy
    else:
        if user_num < enemy_num:
            winner = enemy
        elif user_num > enemy_num:
            winner = user_nickname

    ctx = {
        'user_game': user_game,
        'counter': counter,
        'user_num': user_num,
        'enemy': enemy,
        'enemy_num': enemy_num,
        'winner': winner
    }
    return render(request, 'game/game_detail.html', ctx)

def game_delete(request, pk):
    if request.method == 'POST':
        user_game = Game.objects.get(id=pk)
        user_game.delete()
    return redirect("game:list")

templates/game/game_attack.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>공격하기</title> 
<link rel="stylesheet" href="{%static 'css/game/game_attack.css'%}" />
{% endblock %} {%block content%}

<div class="form-container">
  <form action="{% url 'game:attack_choice' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <div class="form-fields">
      {{ form.as_p }}
    </div>
    <button class="form-btn">¤ 공격하기 ¤</button>
  </form>
</div>
{%endblock%}

templates/game/game_attacking.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>공격중</title>
<link rel="stylesheet" href="{%static 'css/game/game_attack.css'%}" />
{% endblock %} {%block content%}

<div class="wrap">
  <div class="form-container2">
    <p>
      {{game.id}}&nbsp;-&nbsp;{{game.attack_user.nickname}}&nbsp;vs&nbsp;{{game.defend_user.nickname}}
    </p>
    {% if game.game_now %}
    <p>{{game_result}}</p>
    {% else %}
    <p>진행 중</p>
    {% endif %}

    <p>나: {{game.attack_num}}</p>
    <a href="{% url 'game:list'%}"><button id="view-all">전적보기</button></a>
  </div>
</div>
{%endblock%}

templates/game/game_defend.html
{% extends 'base.html' %} {% load static %} {%block head%}
<link rel="stylesheet" href="{%static 'css/game/game_defend.css'%}" />
<title>반격하기</title>{% endblock %} {%block content%}
<div id="defend-container">
  <p>'상대유저'에게 반격합니다.</p>
  <div class="form-container">
    <form action="{% url 'game:defend' pk %}" method="post" enctype="multipart/form-data">
      {%csrf_token%} {{form.as_p}}
      <input type="hidden" name="counter" value="{{ counter }}">
      <button class="form-btn">¤ 반격하기 ¤</button>
    </form>
  </div>
</div>
{%endblock%}

templates/game/game_detail.html
{% extends 'base.html' %} {% load static %} {%block head%}
<link rel="stylesheet" href="{%static 'css/game/game_detail.css'%}" />
<title>게임 정보</title>{% endblock %} {%block content%}
<div class="detail-container">
  <p>{{ counter }} - {{user.nickname}} VS {{ enemy }}</p>

  {% if user_game.now == False %}
    {% if user_game.attack_user.id == user.id %}
    <div class="mode">
      <p>진행 중...</p>
      <p>나: {{ user_num }}</p>
      <form action="{% url 'game:delete' user_game.pk %}" method="post">
        {%csrf_token%}
        <button>게임 취소</button>
      </form>
      <a href="{% url 'game:list'%}"><button id="view-all">전적 목록</button></a>
    </div>
    {% else %}
    <a href="{% url 'game:defend' user_game.pk %}?counter={{ counter }}"><button id="go-defend">대응하기</button></a>
    <a href="{% url 'game:list'%}"><button id="view-all">전체 목록</button></a>
    {% endif %}
  {% else %}
  <div class="mode">
    {% if user_game.game_num == 1 %}
    <p>숫자가 더 작은 사람이 대결에서 이깁니다</p>
    {% else %}
    <p>숫자가 더 큰 사람이 대결에서 이깁니다</p>
    {% endif %}
    <p>나: {{ user_num }}</p>
    <p>{{ enemy }}: {{ enemy_num }}</p>
    {% if winner == user.nickname %}
    <p>결과: 승리</p>
    <p>점수: {{ user_num }}점</p>
    {% elif winner == '' %}
    <p>결과: 무승부</p>
    <p>점수: 0점</p>
    {% else %}
    <p>결과: 패배</p>
    <p>점수: - {{user_num}}점</p>
    {% endif %}
  </div>
  <a href="{% url 'game:list'%}"><button id="view-all">전체 목록</button></a>
  {% endif %}
</div>
{%endblock%}

templates/game/game_list.html
{% extends 'base.html' %} {% load static %} {%block head%}
<link rel="stylesheet" href="{%static 'css/game/game_list.css'%}" />
<title>전적보기</title>{% endblock %}

{%block content%}

<div id="description">
  <p>게임전적</p>
  접속중인 플레이어의 게임 전적을 모두 보여주는 페이지입니다. 게임의 승패에 따라, 당신의 카드에 따라 포인트가 적립, 삭제됩니다. <br />
  진행 중인 게임은 취소할 수 있으며 결과가 나온 게임은 다시 되돌릴 수 없습니다. 또한 플레이어는 공수와 관계없이 왼쪽으로 정렬되어 있습니다.
</div>
<div id="login-info">
  <p><strong>|</strong> 현재 플레이어: {{user.nickname}}</p>
</div>
<div id="game-list">
  {% for user_game in user_games %}
  <div class="game">
    {% if user_game.attack_user.id == user.id %}
    <div class="user-info"><strong>{{ forloop.revcounter }}</strong> - {{user.nickname}} <strong>VS</strong> {{ user_game.defend_user.nickname }}</div>
    {% else %}
    <div class="user-info"><strong>{{ forloop.revcounter }}</strong> - {{user.nickname}}<strong>VS</strong> {{ user_game.attack_user.nickname }}</div>
    {% endif %}

    {% if user_game.now == False %}
      {% if user_game.attack_user.id == user.id %}
      <div class="game-info">
        진행중...
        <form action="{% url 'game:delete' user_game.id %}" method="post">
          {% csrf_token %}
          <button>게임 취소</button>
        </form>
      </div>
      {% else %}
      <div class="game-info">
        진행중...
        <a href="{% url 'game:defend' user_game.id %}?counter={{ forloop.revcounter }}"><button>반격하기</button></a>
      </div>
      {% endif %}
    {% else %}
      {% if user_game.attack_num == user_game.defend_num %}
      <div class="game-info">결과: 무승부</div>
      {% endif %}
      {% if user_game.game_num == 1 %}
        {% if user_game.attack_user.id == user.id %}
          {% if user_game.attack_num < user_game.defend_num %}
          <div class="game-info">결과: 승리</div>
          {% elif user_game.attack_num > user_game.defend_num %}
          <div class="game-info">결과: 패배</div>
          {% endif %}
        {% else %}
          {% if user_game.attack_num < user_game.defend_num %}
          <div class="game-info">결과: 패배</div>
          {% elif user_game.attack_num > user_game.defend_num %}
          <div class="game-info">결과: 승리</div>
          {% endif %}
        {% endif %}
      {% else %}
        {% if user_game.attack_user.id == user.id %}
            {% if user_game.attack_num > user_game.defend_num %}
            <div class="game-info">결과: 승리</div>
            {% elif user_game.attack_num < user_game.defend_num %}
            <div class="game-info">결과: 패배</div>
            {% endif %}
        {% else %}
            {% if user_game.attack_num > user_game.defend_num %}
            <div class="game-info">결과: 패배</div>
            {% elif user_game.attack_num < user_game.defend_num %}
            <div class="game-info">결과: 승리</div>
            {% endif %}
        {% endif %}
      {% endif %}
    {% endif %}
    <a href="{% url 'game:detail' user_game.id %}?counter={{ forloop.revcounter }}">
      <div class="game-detail"><p>게임정보</p></div>
    </a>
  </div>
  {% endfor %}
</div>

{%endblock%}

templates/game/game_login.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{%static 'css/game/game_login.css'%}" />
<title>소셜 로그인</title>
{% endblock %} {% block header %} {% endblock %} {% block content %}
<div id="login-container">
  <div id="login-logo">CARDGAME</div>
  <br />
  <div id="google-btn">
    <div></div>
    <p>구글 계정 로그인</p>
  </div>
  <div id="naver-btn">
    <div></div>
    <p>네이버 계정 로그인</p>
  </div>
</div>
{% endblock %}

templates/game/game_main.html
{% extends 'base.html' %} {% load static %} {%block head%}
<link rel="stylesheet" href="{%static 'css/game/game_main.css'%}" />
<link
  href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
  rel="stylesheet"
/>
<title>게임하기</title>{% endblock %} {%block content%}
<div id="main-container">
  <i class="ri-money-dollar-circle-line"></i>
  <p>전 세계 피로그래머와 한 판 도박</p>
  <p>숫자카드게임</p>
  {%if not user.is_authenticated %}
  <a href="{%url 'users:login'%}">
    <div class="main-btn">게임하기</div>
  </a>
  {%else%}
  <p id="login-info">{{user.nickname}} 님이 로그인 중</p>
  <a href="{%url 'game:attack_choice' %}">

    <div class="main-btn">게임하기</div>
  </a>
  <a href="{%url 'game:list' %}">
    <div class="main-btn">전적보기</div>
  </a>
  {%endif%}
</div>
{%endblock%}