apps/game/urls.py
from django.urls import path,include
from .views import *

app_name='game'

urlpatterns = [
    path('',main,name='main'),
    # path('attack_main/', main, name='attack_main'),
    path('attack', attack, name ='attack'),
    path('attack_choice', attack_choice, name ='attack_choice'),
    path('attacking/<int:pk>', attacking, name ='attacking'),
    path('list/', game_list , name='list'),
#     path('detail/<int:pk>/', detail, name='detail'),
    # path('detail/<int:pk>/', detail, name='detail'),
    path('detail/<int:pk>', game_detail, name='detail'),
#     path('defend/<int:pk>/', defend, name="defend"),
    path('defend/<int:pk>', defend, name="defend"),
    path('delete/<int:pk>', game_delete, name='delete')
]

apps/users/urls.py
from django.urls import path
from .views import *

app_name='users'

urlpatterns = [
    path("",main,name='main'),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("signup/", signup, name="signup"),
    path("ranking/", ranking, name="ranking"),
    path("set_name/", set_name, name="setname"),
    path('delete/<int:pk>/', delete, name ='delete'),
    path('update/<int:pk>/', update, name ='update'),
    #path('detail/<int:pk>/', detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.game.urls')),
    path('users/',include('apps.users.urls')),
    path('accounts/', include('allauth.urls')),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{%static 'css/style.css'%}" />
    {%block head%} {% endblock %}
  </head>
  <body>
    {% block header %}
    <header>
      <a href="{% url 'game:main'%}">
        <div id="logo">CARDGAME</div>
      </a>
      {%if not user.is_authenticated %}
      <a href="{% url 'users:login'%}">
        <div class="header-btn">로그인</div>
      </a>
      {%else %}
      <div id="logining">
        <a href="{% url 'game:attack_choice'%}">
          <div class="header-btn">게임하기</div>
        </a>
        <a href="{% url 'users:ranking'%}">
          <div class="header-btn">랭킹보기</div>
        </a>
        <a href="{% url 'users:logout' %}">
          <div class="header-btn">로그아웃</div>
        </a>
        <a href="{% url 'users:update' user.pk %}">
          <div class="header-btn">계정관리</div>
        </a>
      </div>
      {% endif %}
    </header>
    {% endblock %}
    <main>{%block content%} {%endblock%}</main>
    <footer>
      <p>
        Copyright © 2024 Programming team 5 / 도박은 재미와 엔터테인먼트를
        제공하는 즐거운 활동이지만, 과도한 도박은 심각한 문제를 초래할 수
        있습니다.
      </p>
    </footer>
  </body>
</html>