apps/game/urls.py
from django.urls import path,include
from .views import *

app_name='game'

urlpatterns = [
    path('',main,name='main'),
    # path('attack_main/', main, name='attack_main'),
    path('attack', attack, name ='attack'),
    path('attack_choice', attack_choice, name ='attack_choice'),
    path('attacking/<int:pk>', attacking, name ='attacking'),
    path('list/', game_list , name='list'),
#     path('detail/<int:pk>/', detail, name='detail'),
    # path('detail/<int:pk>/', detail, name='detail'),
    path('detail/<int:pk>', game_detail, name='detail'),
#     path('defend/<int:pk>/', defend, name="defend"),
    path('defend/<int:pk>', defend, name="defend"),
    path('delete/<int:pk>', game_delete, name='delete')
]

apps/users/urls.py
from django.urls import path
from .views import *

app_name='users'

urlpatterns = [
    path("",main,name='main'),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("signup/", signup, name="signup"),
    path("ranking/", ranking, name="ranking"),
    path("set_name/", set_name, name="setname"),
    path('delete/<int:pk>/', delete, name ='delete'),
    path('update/<int:pk>/', update, name ='update'),
    #path('detail/<int:pk>/', detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.game.urls')),
    path('users/',include('apps.users.urls')),
    path('accounts/', include('allauth.urls')),
]

apps/users/models.py
# users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    points=models.IntegerField(default=0)
    nickname=models.CharField(max_length=24, null=False, unique=True)

    def __str__(self):
        return self.nickname

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username','nickname']
        
class NicknameUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['nickname']

apps/users/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from .models import *
from .forms import NicknameUpdateForm
from django.contrib.auth import get_user_model
from allauth.socialaccount.models import SocialAccount

# Create your views here.
def main(request):
    return redirect('game:main')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('game:main')
        else:
            # 유효하지 않은 데이터 처리
            ctx={
                'form':form,
            }           
            return render(request,'users/users_signup.html', ctx)
    else:
        form = SignupForm()
        context = {
            'form': form,
        }
        return render(request, 'users/users_signup.html',context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            if request.user.nickname==None or request.user.nickname=="":
                return render(request, "users/users_setname.html")
            else:
                return redirect('users:main')
        else:
            context = {
                'form': form,
            }
            return render(request, template_name='users/users_login.html', context=context)
    else:
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, template_name='users/users_login.html', context=context)


def logout(request):
    auth.logout(request)
    return redirect('game:main')

def ranking(request):
    rankers=User.objects.order_by("-points")[:5]
    return render(request, "users/users_ranking.html", {'rankers':rankers})

def set_name(request):
    if request.method=="POST":
        user=request.user
        new_name=request.POST["name"]
        if User.objects.filter(nickname=new_name):
            return render(request, "users/users_setname.html", {'error':"이미 존재하는 닉네임 입니다!"})
        else:
            user.nickname=new_name
            user.save()
            return redirect("users:main")
    if request.user.nickname==None or request.user.nickname=="":
        return render(request, "users/users_setname.html")
    else:
        return redirect('game:main')
    
def delete(request, pk):
    if request.method == 'POST':
        User = get_user_model()
        user = User.objects.get(id=pk)
        
        # 소셜 로그인 정보 확인
        social_accounts = SocialAccount.objects.filter(user=user)
        
        # 소셜 로그인 정보 삭제
        for social_account in social_accounts:
            social_account.delete()
        
        # 사용자 삭제
        user.delete()
    
    return redirect('game:main')

def update(request, pk):
    user = User.objects.get(id=pk)
    if request.method == 'GET':
        form = NicknameUpdateForm(instance=user)
        ctx = {'form': form, 'pk': pk}
        return render(request, 'users/users_update.html', ctx)
    form = NicknameUpdateForm(request.POST, instance=user)
    if form.is_valid():
        form.save()
    return redirect('game:main')

templates/users/set_name.html
{% extends '../index.html' %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    새로운 유저이름 : <input name="name" type="text"/>
    <input type="submit" value="SignUp">
</form>
{% endblock content %}

templates/users/users_login.html
{% extends 'base.html' %} {% load socialaccount %} {% load static %} {%
providers_media_js %} {% block head %}
<link rel="stylesheet" href="{%static 'css/users/users_login.css'%}" />
<title>소셜 로그인</title>
{% endblock %}  {% block content %}
<div id="login-container">
  <br />
  <div class="login-form">
    <form method="POST" action="">
      {% csrf_token %}
      <div class="form-element">{{ form }}</div>
      <button class="form-btn">Login</button>
    </form>
  </div>
  <div class="signups">
    <form action="{% provider_login_url 'google' %}" method="post">
      {% csrf_token %}
      <button id="google-btn">
        <div></div>
        <p>구글 로그인</p>
      </button>
    </form>
    <form action="{% provider_login_url 'naver' %}" method="post">
      {% csrf_token %}
      <button id="naver-btn">
        <div></div>
        <p>네이버 로그인</p>
      </button>
    </form>
    <form action="{% provider_login_url 'kakao' %}" method="post">
      {% csrf_token %}
      <button id="kakao-btn">
        <div></div>
        <p>카카오 로그인</p>
      </button>
    </form>
    <form action="{% url 'users:signup'%}" method="get">
      <button id="signup-btn">
        <div></div>
        <p>로컬 회원가입</p>
      </button>
    </form>
  </div>
</div>
{% endblock %}

templates/users/users_ranking.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{%static 'css/users/users_ranking.css'%}" />
<title>랭킹보기</title>
{% endblock %} {% block content %}
<div class="ranking-container">
  <p>Piro20 명예의 전당</p>
  <div class="rank">
    <p style="color:lightgreen;"> 순위 </p>
    <p style="color:lightgreen;"> 닉네임 </p>
    <p style="color:lightgreen;"> 포인트 </p>
  </div>
  {% for ranker in rankers %}
  <div class="rank">
    {% if forloop.counter == 1 %}
      <p>{{ forloop.counter }}등 🏆️ </p>
      <p>{{ranker.nickname}}</p>
      <p>{{ranker.points}} points</p>
    {% elif forloop.counter == 2 %}
      <p>{{ forloop.counter }}등 🥈 </p>
      <p>{{ranker.nickname}}</p>
      <p>{{ranker.points}} points</p>     
    {% elif forloop.counter == 3 %}
      <p>{{ forloop.counter }}등 🥉 </p>
      <p>{{ranker.nickname}}</p>
      <p>{{ranker.points}} points</p>
    {% else %}
      <p>{{ forloop.counter }}등</p>
      <p>{{ranker.nickname}}</p>
      <p>{{ranker.points}} points</p>
    {% endif %}   
  </div>
  {% endfor %}
  <a href="{% url 'game:list'%}"><button id="view-all">전체 목록</button></a>
</div>
{% endblock %}

templates/users/users_setname.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{%static 'css/users/users_signup.css'%}" />
<title>유저 정보 설정</title>
{% endblock %} {% block content %}
<div class="form-container">
  {% if error %}
    <div> {{error}} </div>
  {% endif %}
  <form method="POST" action="">
    {% csrf_token %} 닉네임 생성 : <input name="name" type="text" />
    <br/>
    <input type="submit" value="SignUp" class="form-btn" />
  </form>
</div>
{% endblock content %}

templates/users/users_signup.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{%static 'css/users/users_signup.css'%}" />
<title>회원가입</title>
{% endblock %} {% block content %}
<div class="form-container">
  <div class="form-page">
    <form method="POST" action="">
      {% csrf_token %} {{ form }}
      <input type="submit" value="SignUp" class="form-btn" />
    </form>
  </div>
</div>
{% endblock content %}

templates/users/users_update.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
  <title>Documents</title>
  <link rel="stylesheet" href="{%static 'css/users/users_update.css'%}" />
{% endblock %}

{% block content %}
  <div class="user_wrap">
      <div class="user_u">
          <form
            action="{% url 'users:update' pk %}"
            method="post"
            class="create_form"
          >
            {% csrf_token %}
            <div>
                {{ form.nickname.label_tag }}
                {{ form.nickname }}
            </div>
            <button class="btn-success">수정완료</button>
      </form>
                <form action="{% url 'users:delete' user.pk %}" method="POST" id="detail_form" onsubmit="return confirm('정말 삭제하시겠습니까?');">
                {% csrf_token %}
                <button type="submit" class="btn-danger">계정삭제</button>
                </form>
      </div>
  </div>
{% endblock %}